variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildAndRunCodeAnalysis
  displayName: Build and run code analysis
  pool:
    vmImage: windows-latest
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution with code analysis
    inputs:
      command: build
      projects: '*.sln'
      arguments: -c $(buildConfiguration) -warnaserror

- job: RunTests
  displayName: Run tests on
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
      macOS:
        imageName: 'macOS-latest'
      Windows:
        imageName: 'windows-latest'
  pool:
    vmImage: $(imageName)
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: build
      projects: '*.sln'
      arguments: -c $(buildConfiguration) -p:RunCodeAnalysis=false
  - task: DotNetCoreCLI@2
    displayName: Run integration tests
    timeoutInMinutes: 5
    inputs:
      command: test
      projects: 'test/*/*IntegrationTests.csproj'
      arguments: -c $(buildConfiguration) -s "azure-pipelines.runsettings" --no-build